# Generated by Django 5.1.7 on 2025-03-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherconditions',
            options={'managed': True},
        ),
    ]
